version: "3"

services:
  frontend:
    labels:
      shipyard.route: "/"
    build: "frontend"
    volumes:
      - "./frontend/src:/srv/src"
    ports:
      - "8000:8000"

  backend:
    labels:
      shipyard.route: "/api"
    build: "backend"
    environment:
      AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
      AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
    volumes:
      - "./backend/src:/srv/src"
    ports:
      - "3000:3000"
